### 전역 변수 설정 (실행 환경에 따라 포트 변경 가능)
@host = http://localhost:8080

### 1. 회원가입
POST {{host}}/api/users/join
Content-Type: application/json

{
  "email": "test@ssafy.com",
  "password": "1234",
  "nickname": "여행자",
  "profileImage": "http://img.url/profile.jpg",
  "bio": "안녕하세요! 여행을 좋아합니다."
}

### 2. 로그인 (토큰 자동 저장 스크립트 포함)
POST {{host}}/api/users/login
Content-Type: application/json

{
  "email": "test@ssafy.com",
  "password": "1234"
}

> {%
    // 로그인 응답에서 accessToken을 꺼내서 'authToken'이라는 변수에 저장합니다.
    client.global.set("authToken", response.body.accessToken);
    client.log("토큰 저장 완료: " + response.body.accessToken);
%}

### 3. 게시물 작성 (저장된 토큰 사용)
POST {{host}}/api/posts
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "imageUrl": "http://img.url/jeju.jpg",
  "travelLocation": "제주도",
  "caption": "제주도 바다가 너무 예뻐요!"
}

### 4. 전체 게시물 조회
GET {{host}}/api/posts
Accept: application/json